# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install --only=prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!

      # make the zip file
      - run: npm run zip

      # upload the zip file to circleci
      - store_artifacts:
          path: ./build/bender.zip
          destination: bender_lambda.zip

      # build the docker image
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t abdulah/bender:latest -f ./local.Dockerfile .

      # login
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      # push image to dockerhub
      - run:
          name: Push to dockerhub
          command: |
            docker push abdulah/bender:latest

      # Cache the build folder for the deploy job
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - build

  deploy_to_lambda:
    docker:
      - image: abdulah/awscli:latest
    working_directory: ~/repo
    steps:

      # Restore cache from the build job which contains the
      # build folder that needs to be deployed
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      # Update the Lambda function
      - run:
          name: Updating randomFuturama
          command: aws lambda update-function-code --function-name randomFuturama --zip-file fileb:///home/circleci/repo/build/bender.zip

  deploy_to_gke:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "bender"
      - GOOGLE_PROJECT_ID: "bender-ahsan"
      - GOOGLE_COMPUTE_ZONE: "us-central1"
      - GOOGLE_CLUSTER_NAME: "bender-cluster-1"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: Apply deployments
          command: |
            kubectl apply -f ${HOME}/kubernetes/deployment.yaml
      - run:
          name: Apply service
          command: |
            kubectl apply -f ${HOME}/kubernetes/service.yaml
      - run:
          name: Watch rollout
          command: |
            kubectl rollout status deployment/bender_deployment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_to_lambda:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy_to_gke:
          filters:
            branches:
              only: master
          requires:
            - build

